"""
Loads the region pkl generated by fire_look.py, generates RGBs, and
performs the Flasse and Ceccato fire detection algorithm with a FireDetector.
"""

import pickle as pkl
import numpy as np
import json
from pathlib import Path
from pprint import pprint as ppt

from aes670hw2 import FireDetector
from aes670hw2 import PixelCat
from aes670hw2 import enhance
from aes670hw2 import guitools as gt
from aes670hw2 import geo_plot as gp

region_pkl = Path("data/pkls/20180904_amazon_fire.pkl")
json_path = Path("data/fire_classes.json")
figure_dir = Path("figures/fire_look/")
with region_pkl.open('rb') as pklfp:
    data, info, geo = pkl.load(pklfp)

debug = True
image_path = Path("figures/fire_look/amazon_fire_rgb.png")

""" Load the data and make a PixelCat band for the SWIR-LWIR diff array """
pc = PixelCat(
        [ X[::-1,::-1] for X in data],
        ("LWIR", "SWIR", "VIS"))
pc.set_band(pc.band("SWIR")-pc.band("LWIR"), "IRdiff")
fd = FireDetector()
cand_px = fd.get_candidates(
        pc.band("LWIR"), pc.band("SWIR"), pc.band("VIS")).candidates

""" Get an RGB of the 3 condition bands """
# RGB recipe selected using fire_categories.py
rgb_bands =["IRdiff", "LWIR", "VIS"]
rgb = pc.get_rgb(
        bands=rgb_bands,
        recipes=[lambda X: enhance.linear_gamma_stretch(X),
                 lambda X: enhance.linear_gamma_stretch(X)*(1/3),
                 lambda X: enhance.linear_gamma_stretch(X) ],
        #recipes=[lambda X: enhance.linear_gamma_stretch(X, gamma=.11),
        #         lambda X: enhance.linear_gamma_stretch(X)*(1/3),
        #         lambda X: enhance.linear_gamma_stretch(X, gamma=.13) ],
        show=False, debug=debug)

""" Show the pixels identified as fire candidates """
cand_rgb = enhance.norm_to_uint(np.copy(rgb), 256, np.uint8)
cand_rgb[cand_px] = np.asarray([255, 255, 255])
gt.quick_render(cand_rgb)
gp.generate_raw_image(cand_rgb, figure_dir.joinpath("amazon_fire_FCmask.png"))


""" Modify thresholds and show the new candidates """
#'''
fd.swir_thresh_lbound = 314
fd.lwir_thresh_lbound = 280
fd.swir_lwir_diff_lbound = 15
fd.nir_ref_ubound = .1
#'''
cand_px = fd.get_candidates(
        pc.band("LWIR"), pc.band("SWIR"), pc.band("VIS")).candidates
cand_rgb = enhance.norm_to_uint(np.copy(rgb), 256, np.uint8)
cand_rgb[cand_px] = np.asarray([255, 255, 255])
gt.quick_render(cand_rgb)
gp.generate_raw_image(cand_rgb, figure_dir.joinpath("amazon_fire_mymask.png"))

cand_px = fd.test_candidates(cand_px, pc.band("LWIR"),
                             pc.band("SWIR"), pc.band("VIS"))
cand_rgb = enhance.norm_to_uint(np.copy(rgb), 256, np.uint8)
cand_rgb[cand_px] = np.asarray([255, 255, 255])
gp.generate_raw_image(cand_rgb, figure_dir.joinpath("amazon_full_mycandidates.png"))
